apiVersion: v1
kind: Service
metadata:
  name: minecraft-java
  namespace: minecraft
  labels:
    app: minecraft-java
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: {{ .Values.server.port | default 30565 }}
  selector:
    app: minecraft-java
